name: pikobar_flutter
description: Pusat Informasi & Koordinasi COVID-19 Jawa Barat

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

# GDrive version 1.4.1+13
# PlayStore version 1.4.1+13

version: 1.5.0+14

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # firebase deps
  firebase_core: ^0.4.4+3
  firebase_messaging:
    git:
      url: https://gitlab.com/jdsteam/sapa-warga/sapawarga-flutter-dependencies.git
      path: firebase_messaging
  firebase_remote_config: ^0.3.0+3
  firebase_analytics: ^5.0.11
  firebase_in_app_messaging: ^0.1.1+3
  firebase_auth: ^0.15.5+3
  firebase_crashlytics: ^0.1.1+2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  url_launcher: ^5.4.2
  shared_preferences: ^0.5.6+3
  path_provider: ^1.6.5
  sqflite: ^1.3.0
  http: ^0.12.0+4
  flutter_bloc: ^3.2.0
  meta: ^1.1.8
  equatable: ^1.1.1
  permission_handler: ^5.0.0+hotfix.5
  cached_network_image: ^2.0.0
  carousel_slider: ^1.4.1
  intl: ^0.16.1
  timeago: ^2.0.26
  package_info: ^0.4.0+16
  shimmer: ^1.1.0
  pull_to_refresh: ^1.5.7
  device_info: '>=0.4.2+4 <2.0.0'
  flare_flutter: ^2.0.1
  photo_view: ^0.9.2
  bottom_navigation_badge: ^1.0.3
  fluttertoast: ^3.1.3
  font_awesome_flutter: ^8.7.0
  cloud_firestore: ^0.13.4+2
  flutter_html: ^0.11.1
  flutter_inappwebview: ^2.1.0+1
  flutter_local_notifications: ^1.2.2
  webview_flutter: ^0.3.19+9
  google_sign_in: ^4.2.0
  share: ^0.6.3+1
  geolocator: ^5.3.0
  pinput: ^0.1.10
  pretty_qr_code: ^1.0.1
  esys_flutter_share: ^1.0.2
  flutter_web_browser: ^0.11.0
  device_preview: ^0.4.0+1
  flutter_downloader: ^1.4.2
  grouped_buttons: ^1.0.4
  flutter_cupertino_date_picker: ^1.0.12
  google_maps_flutter: ^0.5.25+3
  flutter_masked_text: ^0.8.0
  app_settings: ^4.0.0
  flutter_pdfview: ^1.0.0+10
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0+1
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/logo/logo.png'

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo/
    - assets/icons/
    - assets/images/
    - assets/fonts/
    - assets/flares/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

  fonts:
    - family: product-sans
      fonts:
        - asset: assets/fonts/product-sans/Product-Sans-Regular.ttf

    - family: source-sans-pro
      fonts:
        - asset: assets/fonts/source-sans-pro/SourceSansPro-Regular.ttf

    - family: intro
      fonts:
        - asset: assets/fonts/intro/Intro.otf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
