name: pikobar_flutter
description: Pusat Informasi & Koordinasi COVID-19 Jawa Barat
publish_to: none

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

# GDrive version 3.0.0+19
# PlayStore version 2.3.0+21

version: 3.0.0+20     # Staging Version

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # firebase deps
  firebase_core: ^0.5.0+1
  firebase_messaging:
    git:
      url: https://github.com/anandarh/flutterfire.git
      path: packages/firebase_messaging
  firebase_remote_config:
    git:
      url: https://github.com/anandarh/flutterfire.git
      path: packages/firebase_remote_config
  firebase_analytics: ^6.1.0
  firebase_in_app_messaging: ^0.2.1
  firebase_auth: ^0.18.2
  firebase_crashlytics: ^0.2.2
  cloud_firestore: ^0.14.2
  cloud_functions: ^0.7.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  eva_icons_flutter: ^2.0.1
  url_launcher: ^5.7.2
  shared_preferences: ^0.5.12+4
  path_provider: ^1.6.18
  sqflite: ^1.3.1+1
  http: ^0.12.2
  flutter_bloc: ^6.0.6
  meta: ^1.2.3
  equatable: ^1.2.5
  permission_handler: ^5.0.1+1
  cached_network_image: ^2.5.1
  carousel_slider: ^3.0.0
  intl: ^0.16.1
  timeago: ^2.0.27
  package_info: ^0.4.3
  shimmer: ^1.1.1
  pull_to_refresh: ^1.6.2
  device_info: ^0.4.2+9
  flare_flutter: ^2.0.6
  photo_view: ^0.10.2
  bottom_navigation_badge: ^1.0.3
  fluttertoast: 7.1.6
  font_awesome_flutter: ^8.9.0
  flutter_html: ^1.0.2
  flutter_inappwebview: ^4.0.0+4
  flutter_local_notifications: ^3.0.1
  google_sign_in: ^4.5.4
  apple_sign_in: ^0.1.0
  share: ^0.6.5+3
  geolocator: ^6.1.4+1
  geocoding: ^1.0.5
  pinput: ^0.2.6
  pretty_qr_code: ^1.0.1
  esys_flutter_share: ^1.0.2
  flutter_web_browser: ^0.12.0
  device_preview: ^0.4.8
  flutter_downloader: ^1.5.1
  grouped_buttons: ^1.0.4
  collection: ^1.15.0-nullsafety.3
  uuid: ^2.2.2
  flutter_sticky_header: ^0.5.0
  overlay_tutorial: ^0.2.1

  # Temporary fix for DiagnosticableMixin not found in the latest flutter version
  # The package on pub.dev hasn't been updated yet
  flutter_cupertino_date_picker:
    git:
      url: https://github.com/anandarh/flutter-cupertino-date-picker.git

  google_maps_flutter: ^1.0.2
  flutter_masked_text: ^0.8.0
  app_settings: ^4.0.4
  flutter_full_pdf_viewer: ^1.0.6
  chips_choice: ^2.0.1
  bubble_tab_indicator: ^0.1.4
  percent_indicator: ^2.1.7+4
  flutter_switch: ^0.1.3
  flutter_background_geolocation: ^1.11.0
  flushbar: ^1.10.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0-nullsafety.1
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/logo/logo.png'

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo/
    - assets/icons/
    - assets/images/
    - assets/fonts/
    - assets/flares/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

  fonts:
    - family: product-sans
      fonts:
        - asset: assets/fonts/product-sans/Product-Sans-Regular.ttf

    - family: source-sans-pro
      fonts:
        - asset: assets/fonts/source-sans-pro/SourceSansPro-Regular.ttf

    - family: intro
      fonts:
        - asset: assets/fonts/intro/Intro.otf

    - family: roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf

    - family: lato
      fonts:
        - asset: assets/fonts/lato/Lato-Regular.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
